
<script type="text/javascript">
var pLang ={ 'lang' : 'english' };
pLang['alertStaff']			= "<?php echo $this->global_mod->db_parse($this->lang->line('alertStaff'));?>";
pLang['alertService']		= "<?php echo $this->global_mod->db_parse($this->lang->line('alertService'));?>";
pLang['today']				= "<?php echo $this->global_mod->db_parse($this->lang->line('today'));?>";
pLang['available']			= "<?php echo $this->global_mod->db_parse($this->lang->line('available'));?>";
pLang['not_Available']		= "<?php echo $this->global_mod->db_parse($this->lang->line('not_Available'));?>";
pLang['not_Available_time'] = "<?php echo $this->global_mod->db_parse($this->lang->line('not_Available_time'));?>";
pLang['more']				= "<?php echo $this->global_mod->db_parse($this->lang->line('more'));?>";
pLang['to']					= "<?php echo $this->global_mod->db_parse($this->lang->line('to'));?>";
pLang['appointment_can_be_taken_only_till']					= "<?php echo $this->global_mod->db_parse($this->lang->line('appointment_can_be_taken_only_till'));?>";
pLang['loading']			= "<?php echo $this->global_mod->db_parse($this->lang->line('loading'));?>";
pLang['click_on_any_slot_to_book_an_appointment'] = "<?php echo $this->global_mod->db_parse($this->lang->line('click_on_any_slot_to_book_an_appointment'));?>";
pLang['night']				= "<?php echo $this->global_mod->db_parse($this->lang->line('night'));?>";
pLang['morning']			= "<?php echo $this->global_mod->db_parse($this->lang->line('morning'));?>";
pLang['afternoon']			= "<?php echo $this->global_mod->db_parse($this->lang->line('afternoon'));?>";
pLang['evening']			="<?php echo  $this->global_mod->db_parse($this->lang->line('evening'));?>";
pLang['contactDetails'] 	= "<?php echo $this->global_mod->db_parse($this->lang->line('contactDetails'));?>";
pLang['pleaseSelect'] 		= "<?php echo $this->global_mod->db_parse($this->lang->line('pleaseSelect'));?>";
pLang['pleaseEnter'] 		= "<?php echo $this->global_mod->db_parse($this->lang->line('pleaseEnter'));?>";
pLang['no_schedule_booking']= "<?php echo $this->global_mod->db_parse($this->lang->line('no_schedule_booking'));?>";
pLang['click_continue']		=  "<?php echo $this->global_mod->db_parse($this->lang->line('click_continue'));?>";
pLang['wrong_coupon'] 		= "<?php echo $this->global_mod->db_parse($this->lang->line('wrong_coupon'));?>";
pLang['successfully_applied'] = "<?php echo $this->global_mod->db_parse($this->lang->line('successfully_applied'));?>";
pLang['pleaseWait'] 		= "<?php echo $this->global_mod->db_parse($this->lang->line('pleaseWait'));?>";
pLang['close'] 				= "<?php echo $this->global_mod->db_parse($this->lang->line('close'));?>";
pLang['unable_recurring_booking'] = "<?php echo $this->global_mod->db_parse($this->lang->line('unable_recurring_booking'));?>";
pLang['email']				= "<?php echo $this->global_mod->db_parse($this->lang->line('email'));?>";
pLang['password']			="<?php echo $this->global_mod->db_parse($this->lang->line('password'));?>";
pLang['remember_me']		="<?php echo $this->global_mod->db_parse($this->lang->line('remember_me'));?>";
pLang['signIn']				="<?php echo $this->global_mod->db_parse($this->lang->line('signIn'));?>";
pLang['cancel']				="<?php echo $this->global_mod->db_parse($this->lang->line('cancel'));?>";
pLang['fPass']				="<?php echo $this->global_mod->db_parse($this->lang->line('fPass'));?>";
pLang['firstLang']			="<?php echo $this->global_mod->db_parse($this->lang->line('firstLang'));?>";
pLang['claickHere']			="<?php echo $this->global_mod->db_parse($this->lang->line('claickHere'));?>";
pLang['faceBookCunnect']	="<?php echo $this->global_mod->db_parse($this->lang->line('faceBookCunnect'));?>";
pLang['faceBookDetails']	="<?php echo $this->global_mod->db_parse($this->lang->line('faceBookDetails'));?>";
pLang['facePopDetails']		= "<?php echo $this->global_mod->db_parse($this->lang->line('facePopDetails'));?>";
pLang['googleCunnect']		= "<?php echo $this->global_mod->db_parse($this->lang->line('googleCunnect'));?>";
pLang['googleLog']			= "<?php echo $this->global_mod->db_parse($this->lang->line('googleLog'));?>";
pLang['googlePopDetails']	= "<?php echo $this->global_mod->db_parse($this->lang->line('googlePopDetails'));?>";
pLang['existsPassword']		= "<?php echo $this->global_mod->db_parse($this->lang->line('existsPassword'));?>";
pLang['invalidEmail']		="<?php echo $this->global_mod->db_parse($this->lang->line('invalidEmail'));?>";
pLang['authentication_Failed'] ="<?php echo $this->global_mod->db_parse($this->lang->line('authentication_Failed'));?>";
pLang['passSent'] 			= "<?php echo $this->global_mod->db_parse($this->lang->line('passSent'));?>";
pLang['invailUserDetails']	= "<?php echo $this->global_mod->db_parse($this->lang->line('invailUserDetails'));?>";
pLang['existEmail']			= "<?php echo $this->global_mod->db_parse($this->lang->line('existEmail'));?>";
pLang['registering']		= "<?php echo $this->global_mod->db_parse($this->lang->line('registering'));?>";
pLang['click_here_continue']="<?php echo $this->global_mod->db_parse($this->lang->line('click_here_continue'));?>";
pLang['upcoming_appointments']="<?php echo $this->global_mod->db_parse($this->lang->line('upcoming_appointments'));?>";
pLang['past_appointments'] 	="<?php echo $this->global_mod->db_parse($this->lang->line('past_appointments'));?>";
pLang['appointment '] 	="<?php echo $this->global_mod->db_parse($this->lang->line('appointment'));?> ";
pLang['mobile_submit']	="<?php echo $this->global_mod->db_parse($this->lang->line('mobile_submit'));?>";

pLang['Mon'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Mon'));?>";
pLang['Tue'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Tue'));?>";
pLang['Wed'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Wed'));?>";
pLang['Thu'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Thu'));?>";
pLang['Fri'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Fri'));?>";
pLang['Sat'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Sat'));?>";
pLang['Sun'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Sun'));?>";

pLang['Monday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Monday'));?>";
pLang['Tuesday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Tuesday'));?>";
pLang['Wednesday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Wednesday'));?>";
pLang['Thursday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Thursday'));?>";
pLang['Friday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Friday'));?>";
pLang['Saturday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Saturday'));?>";
pLang['Sunday'] = "<?php echo $this->global_mod->db_parse($this->lang->line('Sunday'));?>";

pLang['January']		= "<?php echo $this->global_mod->db_parse($this->lang->line('January'));?>";
pLang['February']		= "<?php echo $this->global_mod->db_parse($this->lang->line('February'));?>";
pLang['March']			= "<?php echo $this->global_mod->db_parse($this->lang->line('March'));?>";
pLang['April']			= "<?php echo $this->global_mod->db_parse($this->lang->line('April'));?>";
pLang['May']			= "<?php echo $this->global_mod->db_parse($this->lang->line('May'));?>";
pLang['June']			= "<?php echo $this->global_mod->db_parse($this->lang->line('June'));?>";
pLang['July']			= "<?php echo $this->global_mod->db_parse($this->lang->line('July'));?>";
pLang['August']			= "<?php echo $this->global_mod->db_parse($this->lang->line('August'));?>";
pLang['September']		= "<?php echo $this->global_mod->db_parse($this->lang->line('September'));?>";
pLang['October']		= "<?php echo $this->global_mod->db_parse($this->lang->line('October'));?>";
pLang['November']		= "<?php echo $this->global_mod->db_parse($this->lang->line('November'));?>";
pLang['December']		= "<?php echo $this->global_mod->db_parse($this->lang->line('December'));?>";

pLang['mobile_are_you_sure']		= "<?php echo $this->global_mod->db_parse($this->lang->line('mobile_are_you_sure'));?>";
pLang['mobile_cancelled_successfully']		= "<?php echo $this->global_mod->db_parse($this->lang->line('mobile_cancelled_successfully'));?>";

</script>
